# Main configuration
nekobin:
  # Host and port nekobin will bind to
  host: "0.0.0.0"
  port: ${PORT:80}

  # Maximum length for title, author and content
  max_title_length: 32
  max_author_length: 32
  max_content_length: 65536

# Postgres database configuration
database:
  # Connection string
  uri: "postgres://gtwowealhziuub:2f6dda12657de4f5c38daab471e68be4a7d1b70951f35244971cad216655b1a5@ec2-18-213-133-45.compute-1.amazonaws.com:5432/da6v0gqn61cops"

  # Advanced connection pool settings
  max_idle_conns: 5
  max_open_conns: 20
  conn_max_lifetime: 1800

# Endpoints limits. Maximum requests over period (in seconds)
limits:
  documents:
    # GET /api/documents/:key and GET /raw/:key
    get:
      - amount: 30
        period: 5
      - amount: 10000
        period: 86400

    # POST /api/documents
    post:
      - amount: 10
        period: 60
      - amount: 20
        period: 3600
      - amount: 50
        period: 86400
